spring:
  application:
    name: swagger

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/testproject?useUnicode=true&characterEncoding=utf8
    username: shinhunwoo
    password: a456456!
    driver-class-name: com.mysql.cj.jdbc.Driver